FROM fedora:43

RUN dnf install -y bash curl tar gzip util-linux-script && dnf clean all

WORKDIR /tmp/vwbk-install
COPY install.sh vwbk ./
RUN bash install.sh

ENV PATH="/root/.local/bin:$PATH"

COPY test_vwbk.sh /tmp/test_vwbk.sh
COPY vwbk /root/.local/bin/vwbk
